name: AI Reviewer

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: read
  pull-requests: write

env:
  SG_BOT_TOKEN: ${{ secrets.SG_BOT_TOKEN }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run AI reviewer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SG_BOT_TOKEN: ${{ secrets.SG_BOT_TOKEN }}
        run: node ci/ai-reviewer.mjs


