name: PR Delivery Metrics

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: read

jobs:
  log:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Append delivery log entry
        run: node ci/pr-metrics.mjs

      - name: Commit delivery log
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(management): update delivery log for PR #${{ github.event.pull_request.number }}"
          file_pattern: docs/management/DELIVERY_LOG.md
